name: Build and Publish Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - Dockerfile
      - entrypoint.sh
      - .github/workflows/docker-build.yml
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

env:
  GHCR_IMAGE: ghcr.io/jewgh/claw-hy

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=ghacache-to: type=gha,mode=max
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.GHCR_IMAGE }}:latest
          provenance: false

      - name: Display published tags
        run: |
          echo "Published tags:"
          echo "${GHCR_IMAGE}:latest"
